# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.6'
gem 'devise', '4.7.1'
gem 'devise_token_auth', '1.1.3'
gem 'handlebars', '~> 0.8.0'
gem 'jsonapi-rails', '~> 0.4.0'
gem 'paper_trail', '10.2.0'
gem 'vineti-notifications', path: '../../'
gem 'vineti-client', git: 'git@github.com:vinetiworks/vineti-client.git', tag: 'v0.2.2'
gem 'vineti-config', git: 'git@github.com:vinetiworks/vineti-config.git', tag: 'v3.0.4'
gem 'vineti-templates', git: 'git@github.com:vinetiworks/vineti-templates.git', tag: 'v1.0.3'